apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste-argo
  template:
    metadata:
      labels:
        app: teste-argo
    spec:
      containers:
        - name: teste-argo
          image: oliveirahr/teste-argo:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
